kind: pipeline
name: check

workspace:
  base: /go
  path: src/github.com/dbeliakov/revisor

steps:
- name: build_and_check_backend
  image: golang:1.12
  commands: &build_and_check_backend
  - cd api
  - go build
  - go test ./...

- name: build_and_check_frontend
  commands: &build_and_check_frontend
  - cd client
  - npm install
  - npm run fix-deps
  - npm run lint
  - npm run build

trigger:
  event:
  - pull_request

