kind: pipeline
name: create-docker-img

workspace:
  base: /go
  path: src/github.com/dbeliakov/revisor

steps:
- name: backend
  image: golang
  commands:
  - cd api
  - go build
  - go test ./...

- name: coverage
  image: golang
  commands:
  - cd api
  - go get github.com/mattn/goveralls
  - goveralls -service drone.io
  environment:
    COVERALLS_TOKEN:
      from_secret: coveralls_token

- name: frontend
  image: node:latest
  commands:
  - cd client
  - npm install
  - npm run fix-deps
  - npm run lint
  - npm run build

- name: publish
  image: plugins/docker
  settings:
    repo: dbeliakov/revisor
    tags: ['latest'] # TODO
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: master
    event: push

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: revisor.dbeliakov.ru
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port: 22
    script:
      - cd ~/docker/revisor
      - docker-compose pull
      - docker-compose up -d
  when:
    branch: master
    event: push

