kind: pipeline
name: check

workspace:
  base: /go
  path: src/github.com/dbeliakov/revisor

steps:
- name: build_and_check_backend
  image: golang:1.12
  commands: &build_and_check_backend
  - cd api
  - go build
  - go test ./...

- name: build_and_check_frontend
  commands: &build_and_check_frontend
  - cd client
  - npm install
  - npm run fix-deps
  - npm run lint
  - npm run build

trigger:
  event:
  - pull_request

---
kind: pipeline
name: build-and-deploy

- name: build_backend
  image: golang:1.12
  commands: *build_and_check_backend

- name: build_frontend
  image: node:latest
  commands: *build_and_check_frontend

- name: coverage
  image: golang
  commands:
  - cd api
  - go get github.com/mattn/goveralls
  - goveralls -service drone.io
  environment:
    COVERALLS_TOKEN:
      from_secret: coveralls_token

- name: publish
  image: plugins/docker
  settings:
    repo: dbeliakov/revisor
    tags: ['latest'] # TODO
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: revisor.dbeliakov.ru
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port: 22
    script:
      - cd ~/docker/revisor
      - docker-compose pull
      - docker-compose up -d

trigger:
  branch:
  - master
  event:
  - push
