image: dbeliakov/gitlab-ci-go-npm-env:latest

stages:
- test
- build
#- deploy

test:
    stage: test
    script:
    - export GOPATH=/go-build
    - mkdir -p $GOPATH/src/
    - ln -s `pwd` $GOPATH/src/reviewer
    - cd $GOPATH/src/reviewer/api
    - go test ./...

build:
    stage: build
    script:
    - export GOPATH=/go-build
    - mkdir -p $GOPATH/src/
    - ln -s `pwd` $GOPATH/src/reviewer
    - cd $GOPATH/src/reviewer/api
    - go build
    - cd ../client
    - npm install
    - npm run build
    - cd ../
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.dbeliakov.ru
    - docker build -t registry.gitlab.dbeliakov.ru/dbeliakov/revisor:latest -t registry.gitlab.dbeliakov.ru/dbeliakov/revisor:build$CI_PIPELINE_ID --no-cache .
    - docker push registry.gitlab.dbeliakov.ru/dbeliakov/revisor

#deploy:
#    stage: deploy
#    before_script:
#    - eval $(ssh-agent -s)
#    - bash -c 'ssh-add <(echo "$DEPLOY_KEY")'
#    - mkdir -p ~/.ssh
#    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
#    script:
#    - fab -H $DEPLOY_ADDR deploy

