version: '2'

services:
    database:
        restart: always
        image: mongo
        networks:
        - private
#        volumes:
#        - /srv/docker/you-podcast/mongo:/data/db

    service:
        restart: always
        image: dbeliakov/revisor:0.1
        networks:
        - private
        - web
        depends_on:
        - database
        ports:
        - 8080:80
#        labels:
#        - "traefik.enable=true"
#        - "traefik.backend=revisor.dbeliakov.ru"
#        - "traefik.frontend.rule=Host:revisor.dbeliakov.ru"
#        - "traefik.docker.network=traefikproxy_webgateway"
        environment:
        - MONGO_ADDR=database:27017
        - MONGO_DATABASE=revisor

networks:
    web:
#        external:
#            name: traefikproxy_webgateway
        driver: bridge
    private:
        driver: bridge

