version: '2'

services:
    service:
        restart: always
        image: registry.gitlab.dbeliakov.ru/dbeliakov/revisor:latest
        networks:
        - private
        - web
        ports:
        - 8080:80
        labels:
        - "traefik.enable=true"
        - "traefik.backend=revisor.dbeliakov.ru"
        - "traefik.frontend.rule=Host:revisor.dbeliakov.ru"
        - "traefik.docker.network=traefikproxy_webgateway"
        env_file:
        - config.env
        volumes:
        - /srv/docker/revisor/database/revisor.db:/revisor.db

networks:
    web:
        external:
            name: traefikproxy_webgateway
    private:
        driver: bridge

