version: '2'

services:
    service:
        restart: always
        image: registry.gitlab.dbeliakov.ru/dbeliakov/revisor:latest
        networks:
        - private
        - web
        labels:
        - "traefik.enable=true"
        - "traefik.backend=revisor.dbeliakov.ru"
        - "traefik.frontend.rule=Host:revisor.dbeliakov.ru"
        - "traefik.docker.network=traefik_webgateway"
        env_file:
        - config.env
        volumes:
        - /srv/docker/revisor/database:/database/

networks:
    web:
        external:
            name: traefik_webgateway
    private:
        driver: bridge

